// Package frame implements the ghillie⇄facade instruction frame: a fixed
// 22-byte, big-endian layout that is signed over verbatim.
//
// PROVENANCE. The layout is not this package's decision. It is
// Facade_Instruction_Codec_Pkg (ada-factory ledger 119, source_sha256
// bb82366ddef3211ff7e56998d9a0f841a2815c75eca64d5e9249a14db7bc6405), forged and
// admitted 2026-07-29:
//
//	Command U8 @0 · Protocol U8 @1 · Artifact_Ref U64 @2..9 ·
//	Version U32 @10..13 · Seq U64 @14..21
//
// HONEST LABEL. This Go marshaller is CROSS-CHECKED AGAINST LEDGER 119, NOT
// ITSELF PROVEN. golden_test.go asserts it is byte-identical to the proven Ada
// Encode over a vector set generated by running that core; that is the v0
// mitigation the design sanctions (DRAFT_ghillie_facade_protocol.md §6), and it
// is equivalence on the vectors, not a proof of equivalence everywhere. The
// production replacement is a C-ABI front over 119, for which these vectors
// become the acceptance test.
package frame

import (
	"encoding/binary"
	"errors"
	"fmt"
)

// Size is the exact wire length of an instruction frame in bytes. The signature
// covers these bytes and no others — there is nothing to canonicalise.
const Size = 22

// ProtocolV0 is the only protocol version this terminal speaks. A frame
// carrying any other value is refused at the decode boundary rather than
// guessed at.
const ProtocolV0 = 1

// ErrShortFrame reports a buffer that is not exactly Size bytes long.
var ErrShortFrame = errors.New("frame: wrong length")

// Instruction is the decoded frame. Field types mirror the Ada record exactly;
// Command is left as a raw uint8 here because validating it against the proven
// command enumeration is the gate's business, not the codec's.
type Instruction struct {
	Command     uint8
	Protocol    uint8
	ArtifactRef uint64
	Version     uint32
	Seq         uint64
}

// Marshal renders the instruction as its 22 wire bytes. Plain big-endian, no
// padding, no alignment: see the package comment for what backs that claim.
func (i Instruction) Marshal() [Size]byte {
	var b [Size]byte
	b[0] = i.Command
	b[1] = i.Protocol
	binary.BigEndian.PutUint64(b[2:10], i.ArtifactRef)
	binary.BigEndian.PutUint32(b[10:14], i.Version)
	binary.BigEndian.PutUint64(b[14:22], i.Seq)
	return b
}

// Unmarshal decodes exactly Size bytes into an Instruction. It returns
// ErrShortFrame for any other length; it does not judge the contents.
func Unmarshal(b []byte) (Instruction, error) {
	if len(b) != Size {
		return Instruction{}, fmt.Errorf("%w: got %d bytes, want %d", ErrShortFrame, len(b), Size)
	}
	return Instruction{
		Command:     b[0],
		Protocol:    b[1],
		ArtifactRef: binary.BigEndian.Uint64(b[2:10]),
		Version:     binary.BigEndian.Uint32(b[10:14]),
		Seq:         binary.BigEndian.Uint64(b[14:22]),
	}, nil
}
